// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: booking.proto

package bookingpb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Cargo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArrivalDeadline *timestamp.Timestamp `protobuf:"bytes,1,opt,name=arrival_deadline,json=arrivalDeadline,proto3" json:"arrival_deadline,omitempty"`
	Destination     string               `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Legs            []*Leg               `protobuf:"bytes,3,rep,name=legs,proto3" json:"legs,omitempty"`
	Misrouted       bool                 `protobuf:"varint,4,opt,name=misrouted,proto3" json:"misrouted,omitempty"`
	Origin          string               `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	Routed          bool                 `protobuf:"varint,6,opt,name=routed,proto3" json:"routed,omitempty"`
	TrackingId      string               `protobuf:"bytes,7,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
}

func (x *Cargo) Reset() {
	*x = Cargo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cargo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cargo) ProtoMessage() {}

func (x *Cargo) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cargo.ProtoReflect.Descriptor instead.
func (*Cargo) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{0}
}

func (x *Cargo) GetArrivalDeadline() *timestamp.Timestamp {
	if x != nil {
		return x.ArrivalDeadline
	}
	return nil
}

func (x *Cargo) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Cargo) GetLegs() []*Leg {
	if x != nil {
		return x.Legs
	}
	return nil
}

func (x *Cargo) GetMisrouted() bool {
	if x != nil {
		return x.Misrouted
	}
	return false
}

func (x *Cargo) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Cargo) GetRouted() bool {
	if x != nil {
		return x.Routed
	}
	return false
}

func (x *Cargo) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

type Leg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VoyageNumber   string               `protobuf:"bytes,1,opt,name=voyage_number,json=voyageNumber,proto3" json:"voyage_number,omitempty"`
	LoadLocation   string               `protobuf:"bytes,2,opt,name=load_location,json=loadLocation,proto3" json:"load_location,omitempty"`
	UnloadLocation string               `protobuf:"bytes,3,opt,name=unload_location,json=unloadLocation,proto3" json:"unload_location,omitempty"`
	LoadTime       *timestamp.Timestamp `protobuf:"bytes,4,opt,name=load_time,json=loadTime,proto3" json:"load_time,omitempty"`
	UnloadTime     *timestamp.Timestamp `protobuf:"bytes,5,opt,name=unload_time,json=unloadTime,proto3" json:"unload_time,omitempty"`
}

func (x *Leg) Reset() {
	*x = Leg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Leg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leg) ProtoMessage() {}

func (x *Leg) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leg.ProtoReflect.Descriptor instead.
func (*Leg) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{1}
}

func (x *Leg) GetVoyageNumber() string {
	if x != nil {
		return x.VoyageNumber
	}
	return ""
}

func (x *Leg) GetLoadLocation() string {
	if x != nil {
		return x.LoadLocation
	}
	return ""
}

func (x *Leg) GetUnloadLocation() string {
	if x != nil {
		return x.UnloadLocation
	}
	return ""
}

func (x *Leg) GetLoadTime() *timestamp.Timestamp {
	if x != nil {
		return x.LoadTime
	}
	return nil
}

func (x *Leg) GetUnloadTime() *timestamp.Timestamp {
	if x != nil {
		return x.UnloadTime
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Unlcode string `protobuf:"bytes,1,opt,name=unlcode,proto3" json:"unlcode,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Location) Reset() {
	*x = Location{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{2}
}

func (x *Location) GetUnlcode() string {
	if x != nil {
		return x.Unlcode
	}
	return ""
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Itinerary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Legs []*Leg `protobuf:"bytes,1,rep,name=legs,proto3" json:"legs,omitempty"`
}

func (x *Itinerary) Reset() {
	*x = Itinerary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Itinerary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Itinerary) ProtoMessage() {}

func (x *Itinerary) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Itinerary.ProtoReflect.Descriptor instead.
func (*Itinerary) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{3}
}

func (x *Itinerary) GetLegs() []*Leg {
	if x != nil {
		return x.Legs
	}
	return nil
}

type NewCargoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origin      string               `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination string               `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Deadline    *timestamp.Timestamp `protobuf:"bytes,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
}

func (x *NewCargoRequest) Reset() {
	*x = NewCargoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewCargoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewCargoRequest) ProtoMessage() {}

func (x *NewCargoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewCargoRequest.ProtoReflect.Descriptor instead.
func (*NewCargoRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{4}
}

func (x *NewCargoRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *NewCargoRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *NewCargoRequest) GetDeadline() *timestamp.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type NewCargoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackingId string `protobuf:"bytes,1,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	Err        string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *NewCargoReply) Reset() {
	*x = NewCargoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewCargoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewCargoReply) ProtoMessage() {}

func (x *NewCargoReply) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewCargoReply.ProtoReflect.Descriptor instead.
func (*NewCargoReply) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{5}
}

func (x *NewCargoReply) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

func (x *NewCargoReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type LoadCargoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackingId string `protobuf:"bytes,1,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
}

func (x *LoadCargoRequest) Reset() {
	*x = LoadCargoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadCargoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCargoRequest) ProtoMessage() {}

func (x *LoadCargoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCargoRequest.ProtoReflect.Descriptor instead.
func (*LoadCargoRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{6}
}

func (x *LoadCargoRequest) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

type LoadCargoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cargo *Cargo `protobuf:"bytes,1,opt,name=cargo,proto3" json:"cargo,omitempty"`
	Err   string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *LoadCargoReply) Reset() {
	*x = LoadCargoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadCargoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCargoReply) ProtoMessage() {}

func (x *LoadCargoReply) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCargoReply.ProtoReflect.Descriptor instead.
func (*LoadCargoReply) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{7}
}

func (x *LoadCargoReply) GetCargo() *Cargo {
	if x != nil {
		return x.Cargo
	}
	return nil
}

func (x *LoadCargoReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type RoutesForCargoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackingId string `protobuf:"bytes,1,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
}

func (x *RoutesForCargoRequest) Reset() {
	*x = RoutesForCargoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutesForCargoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutesForCargoRequest) ProtoMessage() {}

func (x *RoutesForCargoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutesForCargoRequest.ProtoReflect.Descriptor instead.
func (*RoutesForCargoRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{8}
}

func (x *RoutesForCargoRequest) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

type RoutesForCargoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Itineraries []*Itinerary `protobuf:"bytes,1,rep,name=itineraries,proto3" json:"itineraries,omitempty"`
}

func (x *RoutesForCargoReply) Reset() {
	*x = RoutesForCargoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutesForCargoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutesForCargoReply) ProtoMessage() {}

func (x *RoutesForCargoReply) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutesForCargoReply.ProtoReflect.Descriptor instead.
func (*RoutesForCargoReply) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{9}
}

func (x *RoutesForCargoReply) GetItineraries() []*Itinerary {
	if x != nil {
		return x.Itineraries
	}
	return nil
}

type CargoToRouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackingId string     `protobuf:"bytes,1,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	Itinerary  *Itinerary `protobuf:"bytes,2,opt,name=itinerary,proto3" json:"itinerary,omitempty"`
}

func (x *CargoToRouteRequest) Reset() {
	*x = CargoToRouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CargoToRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CargoToRouteRequest) ProtoMessage() {}

func (x *CargoToRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CargoToRouteRequest.ProtoReflect.Descriptor instead.
func (*CargoToRouteRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{10}
}

func (x *CargoToRouteRequest) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

func (x *CargoToRouteRequest) GetItinerary() *Itinerary {
	if x != nil {
		return x.Itinerary
	}
	return nil
}

type CargoToRouteReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *CargoToRouteReply) Reset() {
	*x = CargoToRouteReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CargoToRouteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CargoToRouteReply) ProtoMessage() {}

func (x *CargoToRouteReply) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CargoToRouteReply.ProtoReflect.Descriptor instead.
func (*CargoToRouteReply) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{11}
}

func (x *CargoToRouteReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type ChangeDestinationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackingId  string `protobuf:"bytes,1,opt,name=tracking_id,json=trackingId,proto3" json:"tracking_id,omitempty"`
	Destination string `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
}

func (x *ChangeDestinationRequest) Reset() {
	*x = ChangeDestinationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeDestinationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeDestinationRequest) ProtoMessage() {}

func (x *ChangeDestinationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeDestinationRequest.ProtoReflect.Descriptor instead.
func (*ChangeDestinationRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{12}
}

func (x *ChangeDestinationRequest) GetTrackingId() string {
	if x != nil {
		return x.TrackingId
	}
	return ""
}

func (x *ChangeDestinationRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type ChangeDestinationReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *ChangeDestinationReply) Reset() {
	*x = ChangeDestinationReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeDestinationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeDestinationReply) ProtoMessage() {}

func (x *ChangeDestinationReply) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeDestinationReply.ProtoReflect.Descriptor instead.
func (*ChangeDestinationReply) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{13}
}

func (x *ChangeDestinationReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type CargosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CargosRequest) Reset() {
	*x = CargosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CargosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CargosRequest) ProtoMessage() {}

func (x *CargosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CargosRequest.ProtoReflect.Descriptor instead.
func (*CargosRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{14}
}

type CargosReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cargos []*Cargo `protobuf:"bytes,1,rep,name=cargos,proto3" json:"cargos,omitempty"`
}

func (x *CargosReply) Reset() {
	*x = CargosReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CargosReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CargosReply) ProtoMessage() {}

func (x *CargosReply) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CargosReply.ProtoReflect.Descriptor instead.
func (*CargosReply) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{15}
}

func (x *CargosReply) GetCargos() []*Cargo {
	if x != nil {
		return x.Cargos
	}
	return nil
}

type LocationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LocationsRequest) Reset() {
	*x = LocationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationsRequest) ProtoMessage() {}

func (x *LocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationsRequest.ProtoReflect.Descriptor instead.
func (*LocationsRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{16}
}

type LocationsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Locations []*Location `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
}

func (x *LocationsReply) Reset() {
	*x = LocationsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booking_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocationsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationsReply) ProtoMessage() {}

func (x *LocationsReply) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationsReply.ProtoReflect.Descriptor instead.
func (*LocationsReply) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{17}
}

func (x *LocationsReply) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

var File_booking_proto protoreflect.FileDescriptor

var file_booking_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x81, 0x02, 0x0a, 0x05, 0x43, 0x61,
	0x72, 0x67, 0x6f, 0x12, 0x45, 0x0a, 0x10, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x5f, 0x64,
	0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0f, 0x61, 0x72, 0x72, 0x69, 0x76,
	0x61, 0x6c, 0x44, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x04,
	0x6c, 0x65, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x65, 0x67, 0x52, 0x04, 0x6c, 0x65, 0x67, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x6d, 0x69, 0x73, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x6d, 0x69, 0x73, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x22, 0xee, 0x01,
	0x0a, 0x03, 0x4c, 0x65, 0x67, 0x12, 0x23, 0x0a, 0x0d, 0x76, 0x6f, 0x79, 0x61, 0x67, 0x65, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x76, 0x6f,
	0x79, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x6f,
	0x61, 0x64, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x27, 0x0a, 0x0f, 0x75, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x75, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x09, 0x6c, 0x6f, 0x61, 0x64,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x75, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0a, 0x75, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x38,
	0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x6e,
	0x6c, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x6e, 0x6c,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x09, 0x49, 0x74, 0x69, 0x6e,
	0x65, 0x72, 0x61, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x04, 0x6c, 0x65, 0x67, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x65,
	0x67, 0x52, 0x04, 0x6c, 0x65, 0x67, 0x73, 0x22, 0x83, 0x01, 0x0a, 0x0f, 0x4e, 0x65, 0x77, 0x43,
	0x61, 0x72, 0x67, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x08, 0x64, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x42, 0x0a,
	0x0d, 0x4e, 0x65, 0x77, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1f,
	0x0a, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72,
	0x72, 0x22, 0x33, 0x0a, 0x10, 0x4c, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x0e, 0x4c, 0x6f, 0x61, 0x64, 0x43, 0x61,
	0x72, 0x67, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x24, 0x0a, 0x05, 0x63, 0x61, 0x72, 0x67,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x2e, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x52, 0x05, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x12, 0x10,
	0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72,
	0x22, 0x38, 0x0a, 0x15, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x46, 0x6f, 0x72, 0x43, 0x61, 0x72,
	0x67, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x22, 0x4b, 0x0a, 0x13, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x73, 0x46, 0x6f, 0x72, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x34, 0x0a, 0x0b, 0x69, 0x74, 0x69, 0x6e, 0x65, 0x72, 0x61, 0x72, 0x69, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x2e, 0x49, 0x74, 0x69, 0x6e, 0x65, 0x72, 0x61, 0x72, 0x79, 0x52, 0x0b, 0x69, 0x74, 0x69, 0x6e,
	0x65, 0x72, 0x61, 0x72, 0x69, 0x65, 0x73, 0x22, 0x68, 0x0a, 0x13, 0x43, 0x61, 0x72, 0x67, 0x6f,
	0x54, 0x6f, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12,
	0x30, 0x0a, 0x09, 0x69, 0x74, 0x69, 0x6e, 0x65, 0x72, 0x61, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x49, 0x74, 0x69,
	0x6e, 0x65, 0x72, 0x61, 0x72, 0x79, 0x52, 0x09, 0x69, 0x74, 0x69, 0x6e, 0x65, 0x72, 0x61, 0x72,
	0x79, 0x22, 0x25, 0x0a, 0x11, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x54, 0x6f, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x5d, 0x0a, 0x18, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x63, 0x6b,
	0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2a, 0x0a, 0x16, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x65, 0x72, 0x72, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x35, 0x0a, 0x0b, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x26, 0x0a, 0x06, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x61,
	0x72, 0x67, 0x6f, 0x52, 0x06, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x73, 0x22, 0x12, 0x0a, 0x10, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x41, 0x0a, 0x0e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x2f, 0x0a, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x32, 0x9b, 0x04, 0x0a, 0x07, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x42,
	0x0a, 0x0c, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x65, 0x77, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x12, 0x18,
	0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x61, 0x72, 0x67,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x41, 0x0a, 0x09, 0x4c, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x12,
	0x19, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x43, 0x61,
	0x72, 0x67, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x1d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x50, 0x6f, 0x73, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x46, 0x6f,
	0x72, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x12, 0x1e, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x46, 0x6f, 0x72, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67,
	0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x46, 0x6f, 0x72, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x12, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e,
	0x43, 0x61, 0x72, 0x67, 0x6f, 0x54, 0x6f, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x62,
	0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x54, 0x6f, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x54, 0x6f, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x11, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x2e,
	0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x44, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x06, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x73, 0x12, 0x16, 0x2e,
	0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x61, 0x72, 0x67, 0x6f, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e,
	0x43, 0x61, 0x72, 0x67, 0x6f, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x41, 0x0a,
	0x09, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x19, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x51,
	0x61, 0x6c, 0x69, 0x66, 0x61, 0x68, 0x2f, 0x73, 0x68, 0x69, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2f,
	0x70, 0x62, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_booking_proto_rawDescOnce sync.Once
	file_booking_proto_rawDescData = file_booking_proto_rawDesc
)

func file_booking_proto_rawDescGZIP() []byte {
	file_booking_proto_rawDescOnce.Do(func() {
		file_booking_proto_rawDescData = protoimpl.X.CompressGZIP(file_booking_proto_rawDescData)
	})
	return file_booking_proto_rawDescData
}

var file_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_booking_proto_goTypes = []interface{}{
	(*Cargo)(nil),                    // 0: booking.Cargo
	(*Leg)(nil),                      // 1: booking.Leg
	(*Location)(nil),                 // 2: booking.Location
	(*Itinerary)(nil),                // 3: booking.Itinerary
	(*NewCargoRequest)(nil),          // 4: booking.NewCargoRequest
	(*NewCargoReply)(nil),            // 5: booking.NewCargoReply
	(*LoadCargoRequest)(nil),         // 6: booking.LoadCargoRequest
	(*LoadCargoReply)(nil),           // 7: booking.LoadCargoReply
	(*RoutesForCargoRequest)(nil),    // 8: booking.RoutesForCargoRequest
	(*RoutesForCargoReply)(nil),      // 9: booking.RoutesForCargoReply
	(*CargoToRouteRequest)(nil),      // 10: booking.CargoToRouteRequest
	(*CargoToRouteReply)(nil),        // 11: booking.CargoToRouteReply
	(*ChangeDestinationRequest)(nil), // 12: booking.ChangeDestinationRequest
	(*ChangeDestinationReply)(nil),   // 13: booking.ChangeDestinationReply
	(*CargosRequest)(nil),            // 14: booking.CargosRequest
	(*CargosReply)(nil),              // 15: booking.CargosReply
	(*LocationsRequest)(nil),         // 16: booking.LocationsRequest
	(*LocationsReply)(nil),           // 17: booking.LocationsReply
	(*timestamp.Timestamp)(nil),      // 18: google.protobuf.Timestamp
}
var file_booking_proto_depIdxs = []int32{
	18, // 0: booking.Cargo.arrival_deadline:type_name -> google.protobuf.Timestamp
	1,  // 1: booking.Cargo.legs:type_name -> booking.Leg
	18, // 2: booking.Leg.load_time:type_name -> google.protobuf.Timestamp
	18, // 3: booking.Leg.unload_time:type_name -> google.protobuf.Timestamp
	1,  // 4: booking.Itinerary.legs:type_name -> booking.Leg
	18, // 5: booking.NewCargoRequest.deadline:type_name -> google.protobuf.Timestamp
	0,  // 6: booking.LoadCargoReply.cargo:type_name -> booking.Cargo
	3,  // 7: booking.RoutesForCargoReply.itineraries:type_name -> booking.Itinerary
	3,  // 8: booking.CargoToRouteRequest.itinerary:type_name -> booking.Itinerary
	0,  // 9: booking.CargosReply.cargos:type_name -> booking.Cargo
	2,  // 10: booking.LocationsReply.locations:type_name -> booking.Location
	4,  // 11: booking.Booking.BookNewCargo:input_type -> booking.NewCargoRequest
	6,  // 12: booking.Booking.LoadCargo:input_type -> booking.LoadCargoRequest
	8,  // 13: booking.Booking.RequestPossibleRoutesForCargo:input_type -> booking.RoutesForCargoRequest
	10, // 14: booking.Booking.AssignCargoToRoute:input_type -> booking.CargoToRouteRequest
	12, // 15: booking.Booking.ChangeDestination:input_type -> booking.ChangeDestinationRequest
	14, // 16: booking.Booking.Cargos:input_type -> booking.CargosRequest
	16, // 17: booking.Booking.Locations:input_type -> booking.LocationsRequest
	5,  // 18: booking.Booking.BookNewCargo:output_type -> booking.NewCargoReply
	7,  // 19: booking.Booking.LoadCargo:output_type -> booking.LoadCargoReply
	9,  // 20: booking.Booking.RequestPossibleRoutesForCargo:output_type -> booking.RoutesForCargoReply
	11, // 21: booking.Booking.AssignCargoToRoute:output_type -> booking.CargoToRouteReply
	13, // 22: booking.Booking.ChangeDestination:output_type -> booking.ChangeDestinationReply
	15, // 23: booking.Booking.Cargos:output_type -> booking.CargosReply
	17, // 24: booking.Booking.Locations:output_type -> booking.LocationsReply
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_booking_proto_init() }
func file_booking_proto_init() {
	if File_booking_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_booking_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cargo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Leg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Location); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Itinerary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewCargoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewCargoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadCargoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoadCargoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutesForCargoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutesForCargoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CargoToRouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CargoToRouteReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeDestinationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeDestinationReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CargosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CargosReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booking_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocationsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_booking_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_proto_goTypes,
		DependencyIndexes: file_booking_proto_depIdxs,
		MessageInfos:      file_booking_proto_msgTypes,
	}.Build()
	File_booking_proto = out.File
	file_booking_proto_rawDesc = nil
	file_booking_proto_goTypes = nil
	file_booking_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BookingClient is the client API for Booking service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookingClient interface {
	BookNewCargo(ctx context.Context, in *NewCargoRequest, opts ...grpc.CallOption) (*NewCargoReply, error)
	LoadCargo(ctx context.Context, in *LoadCargoRequest, opts ...grpc.CallOption) (*LoadCargoReply, error)
	RequestPossibleRoutesForCargo(ctx context.Context, in *RoutesForCargoRequest, opts ...grpc.CallOption) (*RoutesForCargoReply, error)
	AssignCargoToRoute(ctx context.Context, in *CargoToRouteRequest, opts ...grpc.CallOption) (*CargoToRouteReply, error)
	ChangeDestination(ctx context.Context, in *ChangeDestinationRequest, opts ...grpc.CallOption) (*ChangeDestinationReply, error)
	Cargos(ctx context.Context, in *CargosRequest, opts ...grpc.CallOption) (*CargosReply, error)
	Locations(ctx context.Context, in *LocationsRequest, opts ...grpc.CallOption) (*LocationsReply, error)
}

type bookingClient struct {
	cc grpc.ClientConnInterface
}

func NewBookingClient(cc grpc.ClientConnInterface) BookingClient {
	return &bookingClient{cc}
}

func (c *bookingClient) BookNewCargo(ctx context.Context, in *NewCargoRequest, opts ...grpc.CallOption) (*NewCargoReply, error) {
	out := new(NewCargoReply)
	err := c.cc.Invoke(ctx, "/booking.Booking/BookNewCargo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingClient) LoadCargo(ctx context.Context, in *LoadCargoRequest, opts ...grpc.CallOption) (*LoadCargoReply, error) {
	out := new(LoadCargoReply)
	err := c.cc.Invoke(ctx, "/booking.Booking/LoadCargo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingClient) RequestPossibleRoutesForCargo(ctx context.Context, in *RoutesForCargoRequest, opts ...grpc.CallOption) (*RoutesForCargoReply, error) {
	out := new(RoutesForCargoReply)
	err := c.cc.Invoke(ctx, "/booking.Booking/RequestPossibleRoutesForCargo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingClient) AssignCargoToRoute(ctx context.Context, in *CargoToRouteRequest, opts ...grpc.CallOption) (*CargoToRouteReply, error) {
	out := new(CargoToRouteReply)
	err := c.cc.Invoke(ctx, "/booking.Booking/AssignCargoToRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingClient) ChangeDestination(ctx context.Context, in *ChangeDestinationRequest, opts ...grpc.CallOption) (*ChangeDestinationReply, error) {
	out := new(ChangeDestinationReply)
	err := c.cc.Invoke(ctx, "/booking.Booking/ChangeDestination", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingClient) Cargos(ctx context.Context, in *CargosRequest, opts ...grpc.CallOption) (*CargosReply, error) {
	out := new(CargosReply)
	err := c.cc.Invoke(ctx, "/booking.Booking/Cargos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingClient) Locations(ctx context.Context, in *LocationsRequest, opts ...grpc.CallOption) (*LocationsReply, error) {
	out := new(LocationsReply)
	err := c.cc.Invoke(ctx, "/booking.Booking/Locations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingServer is the server API for Booking service.
type BookingServer interface {
	BookNewCargo(context.Context, *NewCargoRequest) (*NewCargoReply, error)
	LoadCargo(context.Context, *LoadCargoRequest) (*LoadCargoReply, error)
	RequestPossibleRoutesForCargo(context.Context, *RoutesForCargoRequest) (*RoutesForCargoReply, error)
	AssignCargoToRoute(context.Context, *CargoToRouteRequest) (*CargoToRouteReply, error)
	ChangeDestination(context.Context, *ChangeDestinationRequest) (*ChangeDestinationReply, error)
	Cargos(context.Context, *CargosRequest) (*CargosReply, error)
	Locations(context.Context, *LocationsRequest) (*LocationsReply, error)
}

// UnimplementedBookingServer can be embedded to have forward compatible implementations.
type UnimplementedBookingServer struct {
}

func (*UnimplementedBookingServer) BookNewCargo(context.Context, *NewCargoRequest) (*NewCargoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookNewCargo not implemented")
}
func (*UnimplementedBookingServer) LoadCargo(context.Context, *LoadCargoRequest) (*LoadCargoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadCargo not implemented")
}
func (*UnimplementedBookingServer) RequestPossibleRoutesForCargo(context.Context, *RoutesForCargoRequest) (*RoutesForCargoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestPossibleRoutesForCargo not implemented")
}
func (*UnimplementedBookingServer) AssignCargoToRoute(context.Context, *CargoToRouteRequest) (*CargoToRouteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignCargoToRoute not implemented")
}
func (*UnimplementedBookingServer) ChangeDestination(context.Context, *ChangeDestinationRequest) (*ChangeDestinationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeDestination not implemented")
}
func (*UnimplementedBookingServer) Cargos(context.Context, *CargosRequest) (*CargosReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cargos not implemented")
}
func (*UnimplementedBookingServer) Locations(context.Context, *LocationsRequest) (*LocationsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Locations not implemented")
}

func RegisterBookingServer(s *grpc.Server, srv BookingServer) {
	s.RegisterService(&_Booking_serviceDesc, srv)
}

func _Booking_BookNewCargo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewCargoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).BookNewCargo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking.Booking/BookNewCargo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).BookNewCargo(ctx, req.(*NewCargoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Booking_LoadCargo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadCargoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).LoadCargo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking.Booking/LoadCargo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).LoadCargo(ctx, req.(*LoadCargoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Booking_RequestPossibleRoutesForCargo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoutesForCargoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).RequestPossibleRoutesForCargo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking.Booking/RequestPossibleRoutesForCargo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).RequestPossibleRoutesForCargo(ctx, req.(*RoutesForCargoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Booking_AssignCargoToRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CargoToRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).AssignCargoToRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking.Booking/AssignCargoToRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).AssignCargoToRoute(ctx, req.(*CargoToRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Booking_ChangeDestination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeDestinationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).ChangeDestination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking.Booking/ChangeDestination",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).ChangeDestination(ctx, req.(*ChangeDestinationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Booking_Cargos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CargosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).Cargos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking.Booking/Cargos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).Cargos(ctx, req.(*CargosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Booking_Locations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServer).Locations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking.Booking/Locations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServer).Locations(ctx, req.(*LocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Booking_serviceDesc = grpc.ServiceDesc{
	ServiceName: "booking.Booking",
	HandlerType: (*BookingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BookNewCargo",
			Handler:    _Booking_BookNewCargo_Handler,
		},
		{
			MethodName: "LoadCargo",
			Handler:    _Booking_LoadCargo_Handler,
		},
		{
			MethodName: "RequestPossibleRoutesForCargo",
			Handler:    _Booking_RequestPossibleRoutesForCargo_Handler,
		},
		{
			MethodName: "AssignCargoToRoute",
			Handler:    _Booking_AssignCargoToRoute_Handler,
		},
		{
			MethodName: "ChangeDestination",
			Handler:    _Booking_ChangeDestination_Handler,
		},
		{
			MethodName: "Cargos",
			Handler:    _Booking_Cargos_Handler,
		},
		{
			MethodName: "Locations",
			Handler:    _Booking_Locations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "booking.proto",
}
